// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhfoubamoaydsbvgcbiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoZm91YmFtb2F5ZHNidmdjYml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTc1MDYsImV4cCI6MjA3MTQ3MzUwNn0.iDbgyYZWecpis7MzaxVsPG9_y24zZIWKk1NBGDop1ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});